### ISSUE TITLE
Feature Request: Real World Building Generation

### ISSUE THREAD

**Issue by CyborgCabbage** [OpenCubicChunks/CubicWorldGen#104]
I saw that OpenStreetMap has building information (viewable on [this](https://osmbuildings.org/) website). The shapes are pretty simple so I thought it might be possible to build them "live" in-game. Of course I don't how much work this would actually take, so I would understand if it's more trouble than its worth.

**Comment by DaMatrix** [comment]
This would be a feature for [Terra 1:1](https://github.com/orangeadam3/terra121), not Cubic World Gen.
