### ISSUE TITLE
World size/boundaries configuration

### ISSUE THREAD

**Issue by muzikbike** [OpenCubicChunks/CubicWorldGen#120]
- Minimum y, maximum y: this is already configurable in Cubic Chunks by modifying the config, but this is not convenient for world customisation. Since world height limits can vary from world to world (the values are stored in cubicChunksData.dat) it'd be more helpful for CWG to provide an option in the GUI/preset to allow for overwriting this upon generation.
- Minimum x, minimum z, maximum x and maximum z: (defined by the default 30,000,000 wall boundary, not the world border) Would also be convenient to allow for this to be changed (although making it very clear that values above the default 30,000,000 value is unsupported). Practical applications could involve (if this could be configured on a per-dimension basis) making the Nether 8x smaller than the Overworld to better fit the portal scaling functionality and not make setting up nether hubs more than a few million blocks out virtually impossible in many aspects. This could be combined with bedrock walls (#58) for an authentic Legacy Console feel.
- Default world border size: in case you want to make this lower than the min/max x/z for some reason.

There's also the nether portal generation boundary (128 blocks before the xz boundaries in vanilla, should probably stay that way if they become configurable) and the y level below which you get damaged (minimum Y minus 64), which could probably remain at their default values for the time being, as I don't see much value in making them changeable beyond that.

**Comment by Niko-sk2x** [comment]
There are already ways to do it and there really isn't a good usecase for doing it. If you want to limit accessible world size in preset, just make everything below certain height bedrock. World border is customizable in vanilla and CC won't touch it.
