### ISSUE TITLE
Bedrock does not generate at the bottom of CustomCubic worlds

### ISSUE THREAD

**Issue by muzikbike** [OpenCubicChunks/CubicWorldGen#37]
![2019-08-18_21 36 25](https://user-images.githubusercontent.com/52297970/63230120-7ded4100-c200-11e9-83e8-89a692687136.png)

On this topic, it may be worth adding in a feature that allows you to change how many layers of bedrock generate, as well as what block actually generates here.

**Comment by muzikbike** [comment]
is this fixed?

**Comment by Niko-sk2x** [comment]
Done in https://github.com/OpenCubicChunks/CubicWorldGen/commit/dffccf99e693baed9c1a1d685adb06e560806442
