### ISSUE TITLE
Certain CustomCubic options can only be modified through directly editing preset text

### ISSUE THREAD

**Issue by muzikbike** [OpenCubicChunks/CubicWorldGen#46]
![2019-08-18_23 01 04](https://user-images.githubusercontent.com/52297970/63230930-21901e80-c20c-11e9-95f7-ba3586652615.png)

These should preferably have dedicated buttons and sliders implemented.

**Comment by Niko-sk2x** [comment]
Duplicate of https://github.com/OpenCubicChunks/CubicWorldGen/issues/28.

**Comment by Niko-sk2x** [comment]
CubeAreas config will never have any GUI. The target is to replace most of it's functionality with something more user friendly.
