### ISSUE TITLE
Customisable liquid lakes

### ISSUE THREAD

**Issue by muzikbike** [OpenCubicChunks/CubicWorldGen#51]
Currently customisation of water and lava lakes is more or less identical to that of vanilla. I think that instead, lake customisation should be made more in-depth similar to ore customization, especially since mods add their own lakes (e.g. biome-specific Biomes O' Plenty poison lakes) which may not generate in CustomCubic by default.

**Comment by Niko-sk2x** [comment]
This is exactly what I'm working on right now.

**Comment by muzikbike** [comment]
I assume this is completely implemented?

**Comment by Niko-sk2x** [comment]
Yes, closed with 0d679983635f990ef4a0caba13e1a90f44588b7c
