### ISSUE TITLE
Building From Source Gradle Buildscript Compilation Errors

### ISSUE THREAD

**Issue by cjburkey01** [OpenCubicChunks/CubicWorldGen#63]
I'm attempting to build the plugin from source (to get around the world preset reset issue) and I've cloned the repo but when running a gradle command, there are errors within the gradle buildfile. I've made sure that the submodule is downloaded too and I'm using Java 8 (1.8.0_221)

These errors occur when I run any gradle command (I started off trying `./gradlew setupCiWorkspace`)

```
FAILURE: Build failed with an exception.

* Where:
Build file '...\CubicWorldGen\build.gradle.kts' line: 50

* What went wrong:
Script compilation errors:

  Line 050:     isSnapshot = true
                ^ Unresolved reference: isSnapshot

  Line 114:     filePattern = "%s.mixins.json"
                ^ Unresolved reference: filePattern

  Line 115:     defaultRefmap = "cubicgen.refmap.json"
                ^ Unresolved reference: defaultRefmap

  Line 116:     defaultCompatibilityLevel = "JAVA_8"
                ^ Unresolved reference: defaultCompatibilityLevel

  Line 117:     defaultMinVersion = "0.7.10"
                ^ Unresolved reference: defaultMinVersion

  Line 119:     config("cubicgen") {
                ^ Unresolved reference: config

  Line 120:         required = true
                    ^ Unresolved reference: required

  Line 121:         packageName = "io.github.opencubicchunks.cubicchunks.cubicgen.asm.mixin"
                    ^ Unresolved reference: packageName

  Line 122:         conformVisibility = true
                    ^ Unresolved reference: conformVisibility

  Line 123:         injectorsDefaultRequire = 1
                    ^ Unresolved reference: injectorsDefaultRequire

  Line 124:         configurationPlugin = "io.github.opencubicchunks.cubicchunks.cubicgen.asm.CubicGenMixinConfig"
                    ^ Unresolved reference: configurationPlugin

11 errors
```

**Comment by Niko-sk2x** [comment]
You need to do a `--recursive` clone.

**Comment by cjburkey01** [comment]
I actually did forget to do that the first time but that was a different error (I've tried `--recursive` and `--recurse-submodules` but both still yield this error). I have the `buildSrc` submodule, do I have to do something with it before the mod will compile correctly?

**Comment by Niko-sk2x** [comment]
Impossible. Starting with new git clone, you should have the mod compiling. Travis CI build file can prove that it works (it fails at deploy stage, compiling works)

If all you want is latest dev version, you can get it on discord. And it will be easier to answer any questions there.

**Comment by cjburkey01** [comment]
Alright the Discord build works but I'm still unable to build it from source (which I don't need to do but I don't understand why it's not working). Here's what I do:

`git clone --recursive-submodules https://github.com/OpenCubicChunks/CubicWorldGen`

Then: `cd CubicWorldGen` and `./gradlew setupCiWorkspace`

That's when that error appears. My `buildSrc` folder has stuff in it so I know the clone is working (and it gives a different error if I don't do a recursive clone)

**Comment by Niko-sk2x** [comment]
When I try your command I get `error: unknown option `recursive-submodules'` so are you sure you are running that exact command?

I ran this:
```
git clone --recursive https://github.com/OpenCubicChunks/CubicWorldGen
cd CubicWorldGen
./gradlew setupCIWorkspace -g TEST_CACHE
```
(-g sets custom gradle home location, to start with fresh gradle cache)
And that works for me.

**Comment by cjburkey01** [comment]
I tried it with the `--recursive` option too which is the same in this case. I’ll try the `-g` option when I get home tonight because I’m not sure if it’s a cache issue or not.

**Comment by Niko-sk2x** [comment]
The best I can come up with is some weirdly corrupted script compile cache. Or you using your system gradle version running `gradle setupCIWorkspace` instead of `./gradlew setupCIWorkspace`

**Comment by cjburkey01** [comment]
I’ve been making sure I’m running with the wrapper because my local gradle is the latest version and I know that doesn’t work with Forge. I’ll try a new cache location tonight and see if that’s the issue then, I can’t think of any reason it’s not working for me so we’ll see :)

**Comment by Niko-sk2x** [comment]
I know latest gradle versions tend to mess with gradle cache by deleting random "unused" files in it ("unused" being "those that haven't been marked as used recently by any gradle version after around 5.1").
You also seem to be on windows, so I'm not sure what environment you are running it from (cmd? powershell? WSL? WSL2? mingw?).

**Comment by cjburkey01** [comment]
I’m using mingw with Git Bash

**Comment by cjburkey01** [comment]
Sorry it took so long but it was a cache issue, it works fine with the temporary cache location
