### ISSUE TITLE
Lapis Lazuli is faaar too rare.

### ISSUE THREAD

**Issue by Leonetienne** [OpenCubicChunks/CubicWorldGen#68]
Lapis Lazuli is a material needed for enchanting and coloring. It shouldn't be all over mines, but at least not THIS rare.
My 7x7 tunnel has now reached level -255. So far i have found about two stacks of diamonds and 15 lapis lazuli. Wtf.

At least make it as "common" as diamonds...
Can't change my worlds settings, i have put many hours into because it is, logically, already generated.

**Comment by Leonetienne** [comment]
I am now at -300. Still no lapis

**Comment by Leonetienne** [comment]
Found 2 ores at -354. The first ones since crossing the y0 milestone

**Comment by Niko-sk2x** [comment]
With default settings, they should generate at y=16 with similar amounts as vanilla, with the same falloff as you get closer to 0 and 32. That pattern should repeat every 192 blocks (so next Y with a lot of lapis should be -176). If this is actually not the case, comment here.
