### ISSUE TITLE
Exit End portal has stopped generating 

### ISSUE THREAD

**Issue by Hyxaru** [OpenCubicChunks/CubicWorldGen#69]
In versions prior to Cubic Chunks 1010, and when the End dimension is configurated to be cubic (not the default), the central island in the End dimension would properly be featuered with an (unactivated) exit portal frame.
Since Cubic Chunks 1010, it no longer generates in cubic End dimensions. Possibly noteworthy:
-The 10 obsidian pillars generate normally. No issues here.
-The enderdragon spawns normally. No issues here.
-Upon slaying the enderdragon, no exit portal is (re)generated. The dragon egg simply generates on the surface block of X=0, Z=0.
-The end dimension is properly cubic. Blocks can be placed below Y=0 and above Y=256. No issues here.

-In conjunction with the Better Portals mod, the mod appears to search for the not present exit portal, and in doing so it tries to load in massive amount of cubes on the Y axis. This causes the memory to run out.

**Comment by Niko-sk2x** [comment]
Fixed with cc95adc4cd6d947ef90168acc260b57bc4d3881d, 769d44b5710467c7a345f815af76c1c9af9e4838, 31aa4b0016a9073cd0ca691b552320adc5ea5fec
