### ISSUE TITLE
Flat cubic and custom cubic world options come after debug mode

### ISSUE THREAD

**Issue by muzikbike** [OpenCubicChunks/CubicWorldGen#75]
When cycling through the world generation types with shift, debug mode appears before flatcubic and customcubic. Basically the same issue here as https://bugs.mojang.com/browse/MC-128779

![2020-02-03_10 27 26](https://user-images.githubusercontent.com/52297970/73645854-06a54f80-4670-11ea-9ef2-26bc733e2436.png)
![2020-02-03_10 27 29](https://user-images.githubusercontent.com/52297970/73645855-06a54f80-4670-11ea-80a4-11d99f5d645e.png)
![2020-02-03_10 27 31](https://user-images.githubusercontent.com/52297970/73645856-06a54f80-4670-11ea-83d6-9e36d38cce96.png)
![2020-02-03_10 27 34](https://user-images.githubusercontent.com/52297970/73645857-073de600-4670-11ea-87de-c61594e89488.png)

**Comment by Niko-sk2x** [comment]
Not much I can do about in a sane way. That's just registration order. All vanilla world types come before modded. Reordering them manually would probably be possible but very hacky and with a lot of potential to break things for such a minor thing.
