### ISSUE TITLE
Liquid blocks look weird in block selection for mineral veins/lakes

### ISSUE THREAD

**Issue by muzikbike** [OpenCubicChunks/CubicWorldGen#83]
Faces don't seem to render in the correct order.
![2020-02-07_14 39 14](https://user-images.githubusercontent.com/52297970/74038274-cd464a00-49b7-11ea-94f9-3083df6647db.png)
![2020-02-07_14 39 44](https://user-images.githubusercontent.com/52297970/74038276-cddee080-49b7-11ea-909f-97bbab6f4063.png)

**Comment by Niko-sk2x** [comment]
I tried to debug it and can't figure it out. This is very minor, visual transparency issue, so not fixing it. Unless someone is willing to figure it out and PR a fix.
