### ISSUE TITLE
Ore veins: blocks that can be replaced

### ISSUE THREAD

**Issue by muzikbike** [OpenCubicChunks/CubicWorldGen#85]
It appears that vanilla has a parameter which defines what types of blocks an ore vein can generate inside. This appears to be missing from CWG.

https://gist.github.com/tryashtar/2a22bd04394275fefb6b49c348758fd6

Currently only emeralds are different from the rest (excluding nether ores, which fall under #42 anyway) as they only generate within stone, whereas other ores can generate in stone and patches of stone data value variants.

This feature could be used for several new purposes, such as mineral veins which generate floating in the air, or very rare ores which can only generate inside of the content of other ore veins.

**Comment by Niko-sk2x** [comment]
This is already a thing, previously `genInBlockstates`, now `placeBlockWhen` (a more general version, that vanilla doesn't even have in code).
