### ISSUE TITLE
Terrain preview graph does not respect replacer settings

### ISSUE THREAD

**Issue by muzikbike** [OpenCubicChunks/CubicWorldGen#96]
For example,, turning on lava oceans and then navigating there will still display the ocean level as blue instead of changing accordingly.

The graph could check and use the respective map colours of the selected blocks.

![2020-02-17_06 11 05](https://user-images.githubusercontent.com/52297970/74628100-a1ac2800-514c-11ea-8872-f329cec28426.png)
![2020-02-17_06 11 17](https://user-images.githubusercontent.com/52297970/74628102-a2dd5500-514c-11ea-90f3-c1c61407834e.png)

**Comment by Niko-sk2x** [comment]
It's not intended to be accurate representation of block types, just terrain shape. The blue color just represents ocean level. You making it a lava ocean is detail.
